### ISSUE TITLE
برقرار نشدن اتصال نرم افزار puTTY

### ISSUE THREAD

**Issue by hosseye** [iranxray/hope#10]
پس از فعال کردن فایروال و باز کردن پورت موردنظر دیگر نتوانستم به puTTY متصل شوم.مشکل از کجاست؟

**Comment by iranxray** [comment]
سلام، چه خطایی دریافت می‌کنید؟ چرا از ssh ویندوز استفاده نکردید؟

**Comment by myhidhacker** [comment]
> پس از فعال کردن فایروال و باز کردن پورت موردنظر دیگر نتوانستم به puTTY متصل شوم.مشکل از کجاست؟

خیلی وقت‌ها وقتی فایروال رو فعال می‌کنید پورت ۲۲ بسته ست. اگر هیچ‌جوره به سرور دسترسی ندارید باید یه استارتاپ اسکریپت برای باز کردن پورت ۲۲ روی سرور بنویسید و سرور رو مجدد راه‌اندازی کنید.

**Comment by iranxray** [comment]
@hosseye سرور تون رو از کجا تهیه کردید؟ معمولا پروایدر‌ها راهی پیش پاتون می‌زارن که بتونید به کنسول به طریقی دیگه دسترسی پیدا کنید. حتی می‌تونید به پروایدر ایمیل بزنید و درخواست بدید که پورت رو باز کنن.

**Comment by hosseye** [comment]
پورت برای کانفیگ اول باز شد و به درستی بر روی دیوایس دیتا دریافت کرد.اما پس از ستاپ کانفیگ دوم و باز کردن پورت مربوطه،دیگر هیچکدام از کانفیگ ها دیتا دریافت نمی کند.کانکت میشود اما دیتا دریافت نمیکند

**Comment by hosseye** [comment]
![photo_2022-11-26_11-38-29](https://user-images.githubusercontent.com/119042858/204079014-908ab7db-2d9e-48b8-a12a-84c1f78441d0.jpg)
![photo_2022-11-26_11-38-41](https://user-images.githubusercontent.com/119042858/204079017-6f0ce426-9796-4a4c-ac32-eb515b4eb7df.jpg)

**Comment by hosseye** [comment]
![photo_2022-11-26_11-38-29](https://user-images.githubusercontent.com/119042858/204079299-d1a94dd9-4888-477f-b958-1db639163457.jpg)
![photo_2022-11-26_11-38-41](https://user-images.githubusercontent.com/119042858/204079306-5fa84a55-ed4c-4846-91fb-b0b047cfafae.jpg)

**Comment by hosseye** [comment]
![photo_2022-11-26_11-38-29](https://user-images.githubusercontent.com/119042858/204079410-84f5ed9b-98e4-4dff-ba9d-7259bb262875.jpg)
![photo_2022-11-26_11-38-41](https://user-images.githubusercontent.com/119042858/204079413-ec09e7e0-9455-4650-b4a8-5d62f7ea4076.jpg)

**Comment by nneema** [comment]
سلام، متاسفانه من توی مرحله ssh به مشکل برخوردم. ارور:
Permission denied (publickey,password)
رو میده. از بابت درست پیست مردن پسورد مطمئن هستم.
با putty هم امتحان کردم و باز هم همین ارور رو میده.

**Comment by mirsaeedi** [comment]
@nneema سلام
به احتمال بسیار زیاد در Paste‌ کردن پسورد مشکل وجود داره. دقت کنید که در putty برای paste باید صرفا right click بکنید.

**Comment by mirsaeedi** [comment]
@hosseye سلام

۱. آیا مشکل مربوط به ssh برطرف شد؟ امکانش هست به اشتراک بگذارید مشکل چی بود؟
۲. برای اینکه بتوانید تنظیمات را در کلاینت اندروید تغییر دهید، ابتدا لازم هست تا کانکشن رو متوقف کنید. بعد از اینکه متوقف شد، می‌تونید تنظیمات رو ویرایش کنید و بعد از ویرایش همونطور که در [مستند کلاینت اندروید](https://github.com/iranxray/hope/blob/main/install-android.md) توضیح دادیم باید دکمه save رو هم بزنید.

**Comment by iranxray** [comment]
@nneema سلام
به احتمال بسیار زیاد در Paste‌ کردن پسورد مشکل وجود داره. دقت کنید که در putty برای paste باید صرفا right click بکنید.

**Comment by iranxray** [comment]
@hosseye سلام

۱. آیا مشکل مربوط به ssh برطرف شد؟ امکانش هست به اشتراک بگذارید مشکل چی بود؟
۲. برای اینکه بتوانید تنظیمات را در کلاینت اندروید تغییر دهید، ابتدا لازم هست تا کانکشن رو متوقف کنید. بعد از اینکه متوقف شد، می‌تونید تنظیمات رو ویرایش کنید و بعد از ویرایش همونطور که در [مستند کلاینت اندروید](https://github.com/iranxray/hope/blob/main/install-android.md) توضیح دادیم باید دکمه save رو هم بزنید.
۳. همچنین، مطمئن باشید که وضعیت سلامت سرور سبز می‌باشد.

![image](https://user-images.githubusercontent.com/118040490/204112196-4094e5a5-00f4-4740-88fe-1ba54a58859c.png)

**Comment by iranxray** [comment]
سلام @nneema 

احتمالا اشکال در نحوه paste کردن پسورد می‌باشد. در putty برای paste‌ کردن باید صرفا right click کنید و ctrl+v‌ کار نمی کند.

**Comment by djexusus** [comment]
سلام. خبر دارید این روش هنوز کارایی داره یا خیر؟ دوستان من که نبونستن متصل بشن متاسفانه

**Comment by nneema** [comment]
> سلام @nneema
> 
> احتمالا اشکال در نحوه paste کردن پسورد می‌باشد. در putty برای paste‌ کردن باید صرفا right click کنید و ctrl+v‌ کار نمی کند.

سلام، ممنون از پاسختون
بله متاسفانه مشکل از پیست کردن پسورد بود، پسورد رو اینبار دستی نوشتم و درست کار کرد.
تمام مراحل رو رفتم اما متاسفانه مشکل دوستمون رو دارم، به سرور وصل میشه اما دیتایی رد و بدل نمیشه.
سلامت سرور رو هم بررسی کردم و اوکی بود.

**Comment by EMOSUI** [comment]
> > پس از فعال کردن فایروال و باز کردن پورت موردنظر دیگر نتوانستم به puTTY متصل شوم.مشکل از کجاست؟
> 
> خیلی وقت‌ها وقتی فایروال رو فعال می‌کنید پورت ۲۲ بسته ست. اگر هیچ‌جوره به سرور دسترسی ندارید باید یه استارتاپ اسکریپت برای باز کردن پورت ۲۲ روی سرور بنویسید و سرور رو مجدد راه‌اندازی کنید.

میشه لظفاً توضیح بدین چجوری این کار انجام میشه؟

**Comment by hosseye** [comment]
> @hosseye سلام
> 
> ۱. آیا مشکل مربوط به ssh برطرف شد؟ امکانش هست به اشتراک بگذارید مشکل چی بود؟ ۲. برای اینکه بتوانید تنظیمات را در کلاینت اندروید تغییر دهید، ابتدا لازم هست تا کانکشن رو متوقف کنید. بعد از اینکه متوقف شد، می‌تونید تنظیمات رو ویرایش کنید و بعد از ویرایش همونطور که در [مستند کلاینت اندروید](https://github.com/iranxray/hope/blob/main/install-android.md) توضیح دادیم باید دکمه save رو هم بزنید. ۳. همچنین، مطمئن باشید که وضعیت سلامت سرور سبز می‌باشد.
> 
> ![image](https://user-images.githubusercontent.com/118040490/204112196-4094e5a5-00f4-4740-88fe-1ba54a58859c.png)

مشکل ssh با خاموش کردن فایروال برطرف شد.بلافاصله پس از باز کردن پورت ها فایروال باید مجددا غیرفعال شود.
سرور الان بدون مشکل داره کار میکنه و دیوایس ها به اینترنت آزاد متصله فقط نمیدونم در زمان ملی شدن نت هم جوابگو باشه یا خیر

**Comment by nneema** [comment]
> > @hosseye سلام
> > ۱. آیا مشکل مربوط به ssh برطرف شد؟ امکانش هست به اشتراک بگذارید مشکل چی بود؟ ۲. برای اینکه بتوانید تنظیمات را در کلاینت اندروید تغییر دهید، ابتدا لازم هست تا کانکشن رو متوقف کنید. بعد از اینکه متوقف شد، می‌تونید تنظیمات رو ویرایش کنید و بعد از ویرایش همونطور که در [مستند کلاینت اندروید](https://github.com/iranxray/hope/blob/main/install-android.md) توضیح دادیم باید دکمه save رو هم بزنید. ۳. همچنین، مطمئن باشید که وضعیت سلامت سرور سبز می‌باشد.
> > ![image](https://user-images.githubusercontent.com/118040490/204112196-4094e5a5-00f4-4740-88fe-1ba54a58859c.png)
> 
> مشکل ssh با خاموش کردن فایروال برطرف شد.بلافاصله پس از باز کردن پورت ها فایروال باید مجددا غیرفعال شود. سرور الان بدون مشکل داره کار میکنه و دیوایس ها به اینترنت آزاد متصله فقط نمیدونم در زمان ملی شدن نت هم جوابگو باشه یا خیر

ممنون، همین کار رو انجام دادم و درست شد.
ولی چرا باید فایروال غیرفعال بشه؟ دلیلش چیه؟

**Comment by firko** [comment]
> ممنون، همین کار رو انجام دادم و درست شد.
> ولی چرا باید فایروال غیرفعال بشه؟ دلیلش چیه؟

دوست عزیز بعد از اینکه فایروال رو فعال کردید، پورت 22 رو باز کنید. این مشکل حل می شه. دیگه لازم نیست هر بار فایروال رو فعال و غیر فعال کنید.

**Comment by hosseye** [comment]
حق با شماست،اشتباه میکردم

**Comment by iranxray** [comment]
این رشتو رو می‌بندیم. اگه مشکلی بود باز در میان بذارید. دم‌همگی تون گرم.
