### ISSUE TITLE
مشکل اتصال همراه اول

### ISSUE THREAD

**Issue by fathipours** [iranxray/hope#102]
سلام از ظهر تا حالا یوزرهایی که از همراه اول استفاده میکردند به سرور کانکت نمیشن

![8a4000e7-9af6-4e17-aff2-4092d590c694](https://github.com/iranxray/hope/assets/137078291/c3378ccf-371e-477c-a824-a209b22464b1)

**Comment by Phoenix-999** [comment]
درود @fathipours 
البته سوال شما خیلی کلی هست و مشکل شما دلایل زیادی میتونه داشته باشه 
 به هر حال چند روش ساده و ابتدایی که در زیر اشاره میکنم, انجام بدید امیدوارم نتیجه بگیرید

1. مطمئن شوید که IP یا Domain یا subdomain بر روی همراه اول بلاک نشده باشد
VPN خود را قطع کنید و با اینترنت همراه اول از IP یا Domain یا subdomain خود پینگ بگیرید ور مطمئن شوید که Connection Timeout نمی گیرد, در غیر این صورت, بلاک شده اید.


![WhatsApp Image 2023-06-21 at 05 31 19](https://github.com/iranxray/hope/assets/127796122/d18bd435-04b0-4709-8a80-b50577307411)


2. اگر از TLS  استفاده میکنید در اپلیکیشن کاربر مقادیر SNI تغییر دهید, مثلا به هر آدرس وبسایتی که در ایران فیلتر نباشد

![WhatsApp Image 2023-06-21 at 05 31 01](https://github.com/iranxray/hope/assets/127796122/1c6d1f5d-1aa3-4ae0-83a7-829f055718a2)


4.اگر جدیدا پنل خود را به روزرسانی کرده اید, مطمئن شوید که اپلیکیشن کاربر مثلا v2rayNG به آخرین نسخه آپدیت شده باشد, که هسته شما با کانفیگ جدید سازگاری داشته باشد. مخصوصا اگر از Reality استفاده میکنید.



![WhatsApp Image 2023-06-21 at 05 31 02](https://github.com/iranxray/hope/assets/127796122/e6c9e414-6a0a-42b7-98bd-78e2ac4b35e8)![Screenshot 2023-06-21 at 05 59 36](https://github.com/iranxray/hope/assets/127796122/3429c463-b286-4250-9087-2cd655502801)


میتوانید همان کانفیگ را بر روی دستگاه ها مختلف یا اپلیکیشن های متفاوت با ISP همراه اول امتحان کنید که در عیب یابی زودتر به نتیجه برسید.

امیدوارم که مشکل شما با موارد بالا حل شود.
