### ISSUE TITLE
Reality doesn't work on port 443

### ISSUE THREAD

**Issue by mzage31** [iranxray/hope#105]
پورت 444 و هر پورت دیگه ای کار میکنه، 80 و 443 کار نمیکنه با اینکه توسط برنامه دیگه ای هم Listen نمیشن

![image](https://github.com/iranxray/hope/assets/13370906/5746e67b-6daa-40bb-bb4c-aca5112c29b5)
![image](https://github.com/iranxray/hope/assets/13370906/7b063622-7904-4aff-ad73-bcf799f61a86)

```
>> lsof -i -P -n | grep LISTEN
sshd         809 root    3u  IPv4   20564      0t0  TCP *:22 (LISTEN)
sshd         809 root    4u  IPv6   20575      0t0  TCP *:22 (LISTEN)
x-ui      538983 root    7u  IPv6 2390418      0t0  TCP *:8080 (LISTEN)
sshd      543280 root    5u  IPv6 2346543      0t0  TCP [::1]:6010 (LISTEN)
sshd      543280 root    7u  IPv4 2346544      0t0  TCP 127.0.0.1:6010 (LISTEN)
xray-linu 557459 root    3u  IPv4 2395840      0t0  TCP 127.0.0.1:62789 (LISTEN)
xray-linu 557459 root    7u  IPv6 2395844      0t0  TCP *:443 (LISTEN)
```

**Comment by Phoenix-999** [comment]
این کامند ها را به ترتیب اجر کنید,  احتمال زیاد مشکل حل خواهد شد 

`sudo ufw reset`
`sudo ufw allow 80`
`sudo ufw allow 443`

OR 

`ufw allow 80/tcp`
`ufw allow 443/tcp`

**Comment by mzage31** [comment]
مشکل از اینجا نبود ولی با آپدیت حل شد فکر میکنم
