### ISSUE TITLE
استفاده از وب سوکت و CDN

### ISSUE THREAD

**Issue by xxamr** [iranxray/hope#11]
در صورتی که راهنمای بهترین پلتفرم برای استفاده از وب ساکت و CDN را قرار دهید ممنون میشم و یا همینجا راهنمایی کوتاه بفرمایید

**Comment by mirsaeedi** [comment]
سلام. حتما به زودی اضافه می‌کنیم. اما با توجه به تجربه ما استفاده از CDN خارج از کشور، مثل CloudFlare تا حدودی رو سرعت اثر منفی داره.

اما برای راه اندازی باید نکات زیر رو در نظر داشته باشید.

۱. از CDN وقتی می‌تونیم استفاده کنیم که domain‌ داشته باشیم.
۲. برای استفاده از CDN‌ باید از WebSocket‌ استفاده کنیم. فعلا هر دوی VMESS و VLESS امکان پشتیبانی از WebSocket رو دارند. کافی هست که اونجا که کانفیگ رو میسازید به جای tcp از ws استفاده کنید.
۳. برای امنیت بیشتر باید TLS هم فعال کنید و حتما باید از Certificate‌معتبر استفاده کنید. به نظر میاد CloudFlare ترافیک روی Self-Signed Certificate رو عبور نمیده.
۴. مهم‌ترین نکته اینکه CloudFlare در پلن رایگان فقط تعداد محدودی پورت رو روی لایه HTTPS‌ ساپورت می‌کنه. يعنی باید به طور دستی مشخص کنید که کانفیگ شما (VLESS+TLS+WS) باید از یکی از پورت‌های زیر استفاده کنه.

https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports

سوالی بود بفرمایید.

![image](https://user-images.githubusercontent.com/2342405/204111800-49d060d9-3360-471f-8486-da3dfc65d949.png)

**Comment by iranxray** [comment]
سلام. حتما به زودی اضافه می‌کنیم. اما با توجه به تجربه ما استفاده از CDN خارج از کشور، مثل CloudFlare تا حدودی رو سرعت اثر منفی داره.

اما برای راه اندازی باید نکات زیر رو در نظر داشته باشید.

۱. از CDN وقتی می‌تونیم استفاده کنیم که domain‌ داشته باشیم.
۲. برای استفاده از CDN‌ باید از WebSocket‌ استفاده کنیم. فعلا هر دوی VMESS و VLESS امکان پشتیبانی از WebSocket رو دارند. کافی هست که اونجا که کانفیگ رو میسازید به جای tcp از ws استفاده کنید.
۳. برای امنیت بیشتر باید TLS هم فعال کنید و حتما باید از Certificate‌معتبر استفاده کنید. به نظر میاد CloudFlare ترافیک روی Self-Signed Certificate رو عبور نمیده.
۴. مهم‌ترین نکته اینکه CloudFlare در پلن رایگان فقط تعداد محدودی پورت رو روی لایه HTTPS‌ ساپورت می‌کنه. يعنی باید به طور دستی مشخص کنید که کانفیگ شما (VLESS+TLS+WS) باید از یکی از پورت‌های زیر استفاده کنه.

https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports

سوالی بود بفرمایید.

![image](https://user-images.githubusercontent.com/118040490/204112182-88886911-0e56-4238-9710-c3b90f3593a2.png)
