### ISSUE TITLE
Problems of VMESS resolved in xray

### ISSUE THREAD

**Issue by free-the-internet** [iranxray/hope#13]
Please see https://github.com/XTLS/Xray-core/pulls?q=is%3Apr+is%3Amerged+vmess
So, your statement about VMESS is not true anymore.
BTW, thanks for translation and explanation.

**Comment by mirsaeedi** [comment]
سلام، ممنون. امکانش هست که لینک مطلب رو مجدد بگذارید. لینک فعلی به لیست Issue ها میره.

**Comment by iranxray** [comment]
سلام. ممنون. امکانش هست که لینک به مطلب رو بگذارید. لینک فعلی صرفا به pull request ها ارجاع می‌دهد. آیا به موضوع حل مشکل DoS اشاره دارید؟

**Comment by free-the-internet** [comment]
That was a mistake. It looks like the problem still exists.
Closing the issue.

**Comment by iranxray** [comment]
ضعف امنیتی این پروتکل اینجا توضیح داده شده. این وب‌سایت به طور خاص بر روی gfw تحقیق می‌کند.

https://gfw.report/blog/v2ray_weaknesses/en/

**Comment by free-the-internet** [comment]
I serached a bit, seems if you use VMESS + TLS with H2 or TCP option, this problem can be resolved.
