### ISSUE TITLE
 عدم دسترسی به سرور بعد از باز کردن پورت  

### ISSUE THREAD

**Issue by EMOSUI** [iranxray/hope#14]
سلام،

بعد از باز کردن پورت ۸۰ دیگه نمی‌تونم به سرور وصل شم.

روی سایتی که سرور را خریدم هم مثل عکس زیر هم این rule را گذاشتم و هم بدون این rule تست کردم ولی باز هم نشد. چه راهی هست بتونم تغییرات قبلی رو ریست کنم؟

ممنونم از وقتی که گذاشتین و خوندین.

<img width="832" alt="Bildschirm­foto 2022-11-27 um 15 48 15 1" src="https://user-images.githubusercontent.com/119187593/204141484-4ad92c50-2cea-46da-b386-246d21660742.png">

**Comment by firko** [comment]
منم این مشکل رو داشتم، روی داشبورد سایتی که VPS رو خریده بودم گزینه ی ریست کردن فایروال وجود داشت که با ریست کردن فایروال مشکل حل شد. اگر اینگزینه رو ندارید روی داشبوردتون با پشتیبانی شون حرف بزنید احتمالا بتونن درستش کنن. من اینجور متوجه شدم که قبل از فعال کردن فایر وال یه سری پورت های مهم به صورت پیش فرض باز هستن، ولی وقتی که فایروال رو فعال می کنید پورت ها رو می بنده. برای همین اگر فایر وال رو فعال کردید اولین کاری که بعدش باید انجام بدید باز کردن پورت 22 هست که برای SSH استفاده می شه.

**Comment by EMOSUI** [comment]
> 

این سری اول ۲۲ را باز کردم و بعد بقیه رو :))

بله مشکل اینه برای باز کردن ۲۲ نمیذاره از داشبوردی که عکس دادم. در واقع اتفاقی نمیفته و باید از دسترسی پشتیبانی باز بشه. ممنونم.

**Comment by firko** [comment]
> > 
> 
> این سری اول ۲۲ را باز کردم و بعد بقیه رو :))
> 
> بله مشکل اینه برای باز کردن ۲۲ نمیذاره از داشبوردی که عکس دادم. در واقع اتفاقی نمیفته و باید از دسترسی پشتیبانی باز بشه. ممنونم.

برای من بعد از فعال کردن فایروال از همون CMD به راحتی تونستم پورت 22 رو باز کنم. ظاهرا بعد از فعال کردن فایروال تا زمانی که پنجره cmd رو نبستید می تونید با سرور کار کنید ولی اگر ببندید دیگه نمی تونید به سرورتون وصل بشید. برای همین باید حتما بعد ار فعال کردن حتما اول پورت 22 رو باز کنید تا در ارتباطای بعدی تون مشکلی نداشته باشید .
