### ISSUE TITLE
Fail to detect internet connection: io: read/write on close pipe 

### ISSUE THREAD

**Issue by HannahSAMI** [iranxray/hope#15]
Fail to detect internet connection: io: read/write on close pipe  
اگر دوستمون این پیام رو دریافت کرد به چه معنیه. خیلی ممنوم اگر تونستید جواب بدید

**Comment by iranxray** [comment]
سلام دوست عزیز.

اگه این مشکل رو در داخل ایران دارید ولی در خارج نیست، با توجه به تجربه ما در این مدت، این به معنی این هست که احتمالا در کلاینت اندروید فراموش کردن که allowinsecure رو true کرده و بعد هم save کنن. ما دیدیم خیلی ها فراموش می کنن که save رو بزنن. این در مطلب راه اندازی کلاینت اندروید هم توضیح داده شده بود.

لطفا بهمون خبر بدید که با این کار مشکل حل شده یا نه.

**Comment by HannahSAMI** [comment]
خیلی ممنون از جوابتون
گفتن این مرحله رو انجام دادن و نتونستن وصل بشن.
از خارج از ایران روی آیفون امتحان کردم و وصل شده.

**Comment by iranxray** [comment]
برای اینکه مطمئن بشیم مشکل از certificate هست یا نه، لطفا یه کانفیگ VLESS و یا VMESS بدون فعال کردن TLS‌یا XTLS بسازید و امتحان کنید.

**Comment by firko** [comment]
من یه بار این مشکل برام بوجود اومد. اگر دقیق یادم باشه به خاطر این بود که پورت کانفیگم رو گذاشته بودم روی 80، فکر کنم خود نرم افزار از پورت 80 استفاده می کنه و برای همین وقتی کانفیگ روش ست می کنید مشکل پیدا می کنه. پورت رو عوض کردم درست شد.

**Comment by iranxray** [comment]
سلام. آیا VLESS بدون TLS امتحان شد؟

**Comment by sun01234** [comment]
بدون tls xtls وصل شد

**Comment by HannahSAMI** [comment]
> سلام. آیا VLESS بدون TLS امتحان شد؟

سلام. نه نتونست وصل بشه. همون اررور قبلی رو داد

**Comment by HannahSAMI** [comment]
> من یه بار این مشکل برام بوجود اومد. اگر دقیق یادم باشه به خاطر این بود که پورت کانفیگم رو گذاشته بودم روی 80، فکر کنم خود نرم افزار از پورت 80 استفاده می کنه و برای همین وقتی کانفیگ روش ست می کنید مشکل پیدا می کنه. پورت رو عوض کردم درست شد.

پورت ۸۰ نیست. مرسی از جوابتون

**Comment by sun01234** [comment]
> > سلام. آیا VLESS بدون TLS امتحان شد؟



> > من یه بار این مشکل برام بوجود اومد. اگر دقیق یادم باشه به خاطر این بود که پورت کانفیگم رو گذاشته بودم روی 80، فکر کنم خود نرم افزار از پورت 80 استفاده می کنه و برای همین وقتی کانفیگ روش ست می کنید مشکل پیدا می کنه. پورت رو عوض کردم درست شد.
> 
> پورت ۸۰ نیست. مرسی از جوابتون



> > سلام. آیا VLESS بدون TLS امتحان شد؟
> 
> سلام. نه نتونست وصل بشه. همون اررور قبلی رو داد

سلام مجدد من self signed ساختم با تروجان همون error میده ولی با VLESS بدون tls یا xtls وصل شد 
در حالیکه خارج همشون اوکی ان 
VLESS بدون tls امن نیست؟

**Comment by bistoshishom** [comment]
سلام. از داخل ایران با اندروید می تونند استفاده کنند اما با آیفون کار نمیکنه. ممنون میشم راهنمایی کنید

**Comment by arrrmita** [comment]
> 

سلام من هم همین مشکل رو دارم. نه از خارج وصل میشم نه میتونن از داخل وصل بشن.

**Comment by nneema** [comment]
دروود
متاسفانه از دیروز کاملا قطع شده (شیراز)
هم
trojan + xtls
و هم
Vless+xtls
رو امتحان کردن ولی گویا از دیروز قطع شده

**Comment by amirroyani** [comment]
> سلام. آیا VLESS بدون TLS امتحان شد؟

سلام منم همین مشکلو دارم بدون TLS هم مشکل حل نشد

**Comment by amirroyani** [comment]
> > سلام دوست عزیز.
> > اگه این مشکل رو در داخل ایران دارید ولی در خارج نیست، با توجه به تجربه ما در این مدت، این به معنی این هست که احتمالا در کلاینت اندروید فراموش کردن که allowinsecure رو true کرده و بعد هم save کنن. ما دیدیم خیلی ها فراموش می کنن که save رو بزنن. این در مطلب راه اندازی کلاینت اندروید هم توضیح داده شده بود.
> > لطفا بهمون خبر بدید که با این کار مشکل حل شده یا نه.
> 
> ~~ ~دقیقا چیزی که گفتید مشکل من رو حل کرد و متصل شدم بسیار سپاسگزارم~ ~~ ~~ ~تنها این که سرعت دانلود رو روی سرورم امتحان میکردم نزدیک به ۱۰۰ مگابایت بود~ ~~ ~~ ~**الان این سرعتش خیلی پایینه در حد ۱ مگابایت! چی کار کنم بیشتر بشه؟!**~ ~~
> 
> ~~ ~از شدت خوشحالی واقعا دارم بال در میارم~ ~~ ~~ ~پشمام ریخته~ ~~ ~~ ~هم Trojon و هم VLESS رو کانفیگ کردم هر دو وصل میشن و بسیار عالی هست~ ~~ ~~ ~من یک روز کامل الکی و بیهوده وقت گذاشتم برای وایگارد و اوپن‌وی‌پی‌ان که وصلشون کنم~ ~~ ~~ ~نمیدونستم هم وطن عزیز ایرانی ما با زبان شیرین پارسی همچین مخزنی رو تو گیت هاب دارن~ ~~ ~~ ~درود بر شرف دوستانی که اینقدر زحمت کشیدن~ ~~
> 
> دوستان همین تازه متوجه شدم اصلا روی ایرانسل و همراه اول کار نمیکنه من داشتم روی اینترنت دانشگاه آزمایش میکردم و خوشحال شدم که تمام من وصل شدم اما وقتی روی گوشی امتحان کردم نتیجه ای نداشت پس بنظرم به خودتون زحمت ندیدن این همه هزینه کردم سرور خریدم حالا حتی این XRAY هم متصل نمیشه روی اینترنت همراه اگر هم راهی هست که بشه به نحوی این مورد رو دور زد ممنون میشم اطلاع بدید
> 
> از دوستان عزیز خیلی ممنون که زحمت کشیدن و این همه وقت گذاشتن تا در این زمینه ما رو راهنمایی کنن
> 
> به اینترانت سلام کنید چیزی نمونده تا نت ملی

سلام، برای من روی همراه اول کار میکنه ایرانسل رو نمیدونم

**Comment by iranxray** [comment]
سلام رفقا. به نظر میاد سیستم فیلترینگ داره کانکشن‌هایی که cert self‐signed دارن رو با نرخ خیلی بالایی می‌بنده و ارتباط با پروکسی رو مسدود می‌کنه.پیشنهاد ما اینه حتما استراتژی زیر رو امتحان کنید اگه مسدود شدید یا حتی اگه فعلا نشدید.

۱. یک cert معتبر تهیه کنید. این رو در مستندات تهیه cert توضیح دادیم.
۲. با استفاده از cert معتبر یه کانفیگ trojan + tls روی پورت ۴۴۳ بسازید.به نظر میاد داشتن پورت‌های متعدد باز روی سرور می‌تونه مشکل زا باشه. از این جهت که سیستم فیلترینگ حساس میشه که چرا یه سرور خارجی باید پورت‌های عجیب غریب و متعدد باز کرده باشه. برای همین سعی کنید برای مصارف شخصی فقط از یک کانفیگ رو پورت ۴۴۳ استفاده کنید و بقیه کانفیگ‌ها رو غیر فعال کنید.

**Comment by bistoshishom** [comment]
سلام دوستان، من cert معتبر تهیه کردم و همه چیز درست پیش رفت اما پرتال از طریق http://Domain:port باز نمیشه و مثل سابق http://ip:port فقط باز میشه. مشکل چی هست؟ ممنونم
