### ISSUE TITLE
نیاز به سرور ایران؟

### ISSUE THREAD

**Issue by mamadxray** [iranxray/hope#2]
سلام دمتون گرم بابت این ریپو 
الان برای استفاده از xray نیازی به سرور ایران نیست اصلا؟ یا بسته به شرایط نیاز میشه؟ مثلا موقع قطعی کامل ترافیک بین الملل 
اگر نیاز نیست که هیچ، ولی ااگر هست دوستان راهنمای کانفیگ سرور ایران هم بذارن عالی میشه (البته اگر فرق داره با سرور خارج)

**Comment by alirezaac** [comment]
سلام اون رو نمیشه به عموم توصیه کرد به دلایل امنیت و هویت فرد،تاثیر خاصی ام نداره مگر اینکه ترافیک قطع بشه که بازم بهتره بهش تکیه نشه.

**Comment by iranxray** [comment]
سلام. در شرایط فعلی برای استفاده از xray هیچ نیازی به سرور داخل ایران نیست. همین امر کمک کرده تا بچه‌های خارج از کشور بتونند به دوست و آشنا در داخل اینترنت آزاد برسونن.
