### ISSUE TITLE
Add cloud-init

### ISSUE THREAD

**Issue by hiddify** [iranxray/hope#21]
Would you please add cloud init script and deploy button for helping people for setup this system without even ssh?

You can find a one-click setup for oracle cloud in my repository

Oracle: [![Deploy to Oracle Cloud](https://oci-resourcemanager-plugin.plugins.oci.oraclecloud.com/latest/deploy-to-oracle-cloud.svg)](https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=https://github.com/hiddify/hiddify-config/archive/refs/heads/main.zip)

or you can find cloud-init script for deploying in any hosting that support it.
In the following you can find our cloud-init script. which is very simple to use
```
#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - gnupg-agent
  - software-properties-common
  - git

runcmd:
  - cd /opt
  - git clone https://github.com/hiddify/hiddify-config/
  - cd hiddify-config
 # uncomment it for using a special secret otherwise it will be createed automatically
 # - echo "USER_SECRET=0123456789abcdef0123456789abcdef" >config.env
 # - echo "MAIN_DOMAIN=" >>config.env
  - echo "TELEGRAM_AD_TAG=" >>config.env
  - bash install.sh

final_message: "The system is finally up, after $UPTIME seconds"
output: { all: "| tee -a /root/cloud-init-output.log" }

# you can see the generated link from the website by using http://yourip/ in one hour after that it will be disappear
```

**Comment by iranxray** [comment]
ممنون. برای ساده‌سازی فرایند ما پروژه جعبه ابزار امید رو راه اندازی کردیم.

https://github.com/iranxray/hope-toolbox/blob/main/README.md
