### ISSUE TITLE
Dealing with active probing

### ISSUE THREAD

**Issue by manizand** [iranxray/hope#22]
سلام
یک سوالی داشتم
وقتی ترافیک یک سرور خیلی بالا بره فیلترچی میاد و چک میکنه که این سرور چیه، و اگر چیز پر ترافیکی (مثل یک وب سرور شلوغ) پیدا نکنه آیپی سرور رو فیلتر میکنه.
روی سروری که x-ui نصب شده چطوری میشه در خواست های ورودی رو چک کرد و اگر از سمت client نبود وانمود کرد که یک وب سرور هستش؟

**Comment by poorp** [comment]
میتونید از torjanpanel استفاده کنید که این کار رو اتوماتیک انجام میده. خودتون هم میتونید با caddy و ufw یه همچین کاری بکنید

**Comment by ea1234567** [comment]
> میتونید از torjanpanel استفاده کنید که این کار رو اتوماتیک انجام میده. خودتون هم میتونید با caddy و ufw یه همچین کاری بکنید

میشه بنده رو راهنمایی کنید؟
من کانفیگ vless دارم (بدون پنل) با پورت 443
الان بخوام یه سایت هم براش فعال کنم (fallback) اونم پورتش میشه 443 چون https هست
اینجوری که تداخل میشه توی پورت 433

**Comment by poorp** [comment]
باید از پورت دیگه ای استفاده کنی قاعدتا برای vless

**Comment by iranxray** [comment]
سلام. در گروه تلگرامی می‌تونید عضو بشید و جواب این سوال ‌ها رو پیدا کنید. ممنون.
