### ISSUE TITLE
مشکل با دریافت پوش نوتیفیکیشن

### ISSUE THREAD

**Issue by sinasaeedi** [iranxray/hope#25]
سلام
توی چند تا گوشی آیفون دیدم که پوش نوتیفیکشن دریافت نمی‌شه. مثلا تلگرام رو باز می‌کنی و می‌بینی که ۴ ساعت قبل پیام داشتی اما نوتیفیکشن بهت نمایش نداده. محدود به تلگرام هم نیست و روی اپ‌های مختلف اینجوریه.
با توجه به اینکه آدرس APNS یا همون Apple Push Notification Service فیلتر نیست، وقتی VPN قطعه پوش میاد اما وقتی وصله نه.

تست‌ها:
روی x-ui ورژن xray رو عوض کردم اما تغییری نکرد.
روش‌های تست شده: vless با xtls با دامین و سرتیفیکیت معتبر. trojan با xtls با دامین و سرتیفیکیت معتبر.
کلاینت رو عوض کردم اما تغییری نکرد: OneClick و Fair
دامین مورد استفاده رو عوض کردم و سرتیفیکیت‌های جدید ایجاد کردم اما تغییری نکرد.

نکته:
در تمام حالت‌ها و تست‌ها ارتباط با اینترنت آزاد برقرار هست و مشکلی از این بابت نیست.

**Comment by DaSpaceJesus** [comment]
منم همین مشکلو دارم گاهی وقتا. یه مشکل دیگه هم که دارم یه سری از اپ های اپل برام وقتی وی پی ان روشنه کار نمیکنن مثل imessage و apple music و فیستایم در صورتی که اینترنت هم دارم با vpn.

**Comment by hossein-mohseni** [comment]
> سلام توی چند تا گوشی آیفون دیدم که پوش نوتیفیکشن دریافت نمی‌شه. مثلا تلگرام رو باز می‌کنی و می‌بینی که ۴ ساعت قبل پیام داشتی اما نوتیفیکشن بهت نمایش نداده. محدود به تلگرام هم نیست و روی اپ‌های مختلف اینجوریه. با توجه به اینکه آدرس APNS یا همون Apple Push Notification Service فیلتر نیست، وقتی VPN قطعه پوش میاد اما وقتی وصله نه.
> 
> تست‌ها: روی x-ui ورژن xray رو عوض کردم اما تغییری نکرد. روش‌های تست شده: vless با xtls با دامین و سرتیفیکیت معتبر. trojan با xtls با دامین و سرتیفیکیت معتبر. کلاینت رو عوض کردم اما تغییری نکرد: OneClick و Fair دامین مورد استفاده رو عوض کردم و سرتیفیکیت‌های جدید ایجاد کردم اما تغییری نکرد.
> 
> نکته: در تمام حالت‌ها و تست‌ها ارتباط با اینترنت آزاد برقرار هست و مشکلی از این بابت نیست.

اسکریپت حل مشکل ریکپچا رو نصب کردین؟
ممکنه به خاطر فایروال خود اپل باشه.

**Comment by sinasaeedi** [comment]
@hossein-mohseni 
این اسکریپت که می‌گی رو نمی‌دونم چیه و کجاست.
لینکش رو ممکنه بدی یه بررسی بکنم؟

**Comment by hossein-mohseni** [comment]
> @hossein-mohseni این اسکریپت که می‌گی رو نمی‌دونم چیه و کجاست. لینکش رو ممکنه بدی یه بررسی بکنم؟

curl -O https://raw.githubusercontent.com/jinwyp/one_click_script/master/install_kernel.sh && chmod +x ./install_kernel.sh && ./install_kernel.sh
