### ISSUE TITLE
domain issue

### ISSUE THREAD

**Issue by Hogoseda11** [iranxray/hope#26]
هنگام ساخت certificate از روش اول وقتی یک domain دلخواه را در command وارد میکنم با خطا مواجه میشود.پورت 80 باز است

![587587](https://user-images.githubusercontent.com/116548495/209726751-17f9f445-6064-47f4-ab51-4d98a406086c.PNG)

**Comment by iranxray** [comment]
سلام دوست عزیز. خطایی که داده شده گویای اینه که تنظیمات DNS انجام نشده. آیا شما تنظیمات لازم رو انجام دادید که domain خریداری شده به IP سرور تون اشاره کنه؟
