### ISSUE TITLE
مشکل با آیفون

### ISSUE THREAD

**Issue by lxvsrvclt** [iranxray/hope#27]
سلام
من سرور برای تروجان درست کردم. بدون مشکل با اندروید کار میکند ولی با آیفون نه. در آیفون کانکت میشه و اون بالا مینویسد کانکت ولی اینترنت کار نمیکنه. نه در داخل ایران نه خارج ایران
همین مشکل با vless است
DNS and Certificate are valid.

**Comment by me-dira** [comment]
سلام،  اعلام کنین که آیا از ssl یا tls استفاده میکنین برای سرورتون یا خیر؟ چون همیشه این مشکل با آیفون بوده و هست و البته چیز بدی نیست بخاطر امنیت خود شماست
لطفا اطلاعات بیشتری از مدل و ورژن سیستم عامل یا نرم‌افزاری که کانکت میشید قرار بدین و منتشر کنید.
### مهم
مورد بعدی که به نظرم اگر اون رو ندارین اصلا هیچ کدوم از این پروتوکول‌ها به درد نمیخوره اینه که، همیشه ssl یا tls رو برای سرورتون فعال داشته باشید. اگر از این دو متد برای رمزگزاری استفاده نکنید، به راحتی ترافیکی که استفاده میکنید شناسایی میشه و بلاک میشه.

**Comment by lxvsrvclt** [comment]
سلام، ممنون از پاسختان
کجا میتونم چک بکنم؟ ببخشید زیاد وارد نیستم، من کامل طبق آموزش های همین صفحه انجام دادم.

**Comment by me-dira** [comment]
> 

وقتی سرور رو اضافه کردین میتونین ویرایش رو بزنین و دوتا مشخصه داره:
- آدرس با https شروع میشه.
- یه قسمت هست که زده tls اون روی tls یا xtls  ست شده باشه.

**Comment by lxvsrvclt** [comment]
آدرس (URL) کنترل پنل (جایی که کانفیگ میسازیم) سبز و Secure است.
در قسمت کانفیگ هم TLS روشن:
![Capture0101](https://user-images.githubusercontent.com/121744749/210183608-352a819a-e15e-470e-8dd1-87b9b1ef46cf.JPG)

**Comment by iranxray** [comment]
گاهی این ابزار‌ها باگ دارند. هر دوی Shadowlink و NapsternetV را نصب داشته باشید. علی‌القاعده نباید مشکلی در آیفون باشد.
