### ISSUE TITLE
اضافه‌کردن دو نکته به فایل open-server-port

### ISSUE THREAD

**Issue by omidgolparvar** [iranxray/hope#30]
سلام. وقتت بخیر.

چندتا مورد رو لطفا بررسی کنین.

در مورد فایل open-server-port.md این نکات به نظرم اضافه بشه.

مورد اول اینکه در برخی (یا شاید همه) ارائه‌دهندگان سرور، ممکنه پورت‌ها بصورت پیش‌فرض بسته باشن، و نیاز باشه کاربر براساس نیازش ابتدا اونا رو باز کنه، تا درخواست‌های دریافتی از **فایروال پنل ارائه‌دهنده** رد بشه و به سرور کاربر برسه.

در واقع روند بازکردن پورت‌ها باید هم در پنل ارائه‌دهنده، و هم در فایروال سرور انجام بشه. در صورتی که هرکدوم از این دو فایروال (فایروال پنل و فایروال سرور) اجازه عبور درخواست روی پورت رو نداشته باشن، سرویس تعریف‌شده به درستی کار نمی‌کنه.

---

مورد دوم اینکه بعد از فعال‌سازی فایروال با استفاده از `ufw`، ابتدا پورت SSH باز بشه. 

چون مطابق با [مستندات DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-18-04) تنظیمات پیشفرض `ufw` به این صورت هست که اجازه هیچ درخواست ورودی رو نده. در نتیجه  بعد از فعال‌سازی `ufw`، پورت SSH (یا همون ۲۲) باز نیست و کاربر امکان اتصال مجدد به سرور از طریق SSH رو نداره.

به مستندات شما این مورد اضافه بشه که بعد از فعال‌سازی `ufw` ابتدا این پورت باز بشه:

```bash
sudo ufw allow ssh
```
و یا:

```bash
sudo ufw allow 22
```

**Comment by iranxray** [comment]
ممنون. نکته خیلی خوبیه. ما در مستندات فرایند رو برای vultr توضیح دادیم و اشاره کردیم در بقیه موارد باید به مستندات ارائه دهنده رجوع بشه.
مورد دوم هم عالی بود. اصلاح شد.

**Comment by iranxray** [comment]
لینک مطلب به روز شده.

https://github.com/iranxray/hope/blob/main/open-server-port.md

بسیار ممنون.
