### ISSUE TITLE
سرور مناسب برای نصب

### ISSUE THREAD

**Issue by ej24831** [iranxray/hope#31]
با سلام
و کمال تشکر از این همه توضیحات روان و قابل درک برای همگان
یه سوال داشتم
حداقل RAM و CPU چند باید باشه برای خرید VPS؟
((چون من VPS با 2 گیگ RAM و با 2 گیگ CPU داشتم
ولی بعد نصب xray
 VPS 
من هنگ کرد و مجبور به REBUILD شدم))

**Comment by abolphazl** [comment]
سلام
بنده یه سرور با 512 مگ رم و پردازنده 1 هسته گرفتم و الان هم x-ui بدون مشکل کار میکنه و هم پروکسی تلگرام ساختم
ولی برای استفاده شخصی و دوستان نزدیک

**Comment by iranxray** [comment]
مهم‌تر از CPU و Memory میزان پهنای باند و ترافیک ماهانه است.
