### ISSUE TITLE
حذف x-ui

### ISSUE THREAD

**Issue by abolphazl** [iranxray/hope#33]
سلام و درود
لطفا آموزش حذف x-ui رو هم قرار بدید.
قصد دارم منابع سرورم رو آزاد کنم.

**Comment by iranxray** [comment]
سلام عزیزم. به سرور ssh بزنید. دستور `x-ui` رو وارد کنید. بهتون یک سری پیشنهاد ارائه میشه که یکیش حذف X-UI هست.
