### ISSUE TITLE
allowinsecure چیست؟

### ISSUE THREAD

**Issue by theduckperson** [iranxray/hope#38]
سلام. `allowinsecure` دقیقا چیکار می‌کنه؟
فقط به کلاینت می‌گه که سرتیفیکیت مقصد رو بررسی نکنه یا کلا دیتا رو رمزنگاری tls نمی‌کنه؟ (و در نتیجه باعث man-in-the-middle و عدم امنیت استفاده کننده می‌شه؟)

**Comment by iranxray** [comment]
سلام دوست عزیز. 

نکته اول: اگه اپلیکیشن تماس HTTPS با مقصد برقرار بکنه، در هر حال داده کاربر رمزنگاری خواهد شد. چه شما با TLS کانفیگ رو ساخته باشی و چه نه.

نکته دوم: داستان این TLS یا XTLS چیه؟ داستان اینه که V2RayNG و باقی کلاینت ها، در مرحله اول یه packet به سمت پروکسی سرور ارسال می کنن و در اونجا به پروکسی سرور درخواست میدن با چه مقصدی تونل ایجاد کنه. مثلا پکت اول میگه یه تونل با تلگرام یا توییتر ایجاد کن بین مقصد (سرور تلگرام) و مبدا (گوشی کاربر). این TLS یا XTLS کاری که می کنه اینه که پکت اول رو رمز می کنه تا فیلترچی متوجه محتویات packet اول نشه. این بسته یه فرمت مشخص داره و اگه خونده بشه لو میره که پروکسی سرور هست. اما در هر حال اگه تونل بین مقصد و مبدا https باشه (که 99 درصد همیشه هست)، داده کاربر قابل شنود نیست.

نکته سوم: حالا این allow insecure چیکار می کنه. وقتی ترافیک مبتنی بر TLS باشه، کلاینت باید تصدیق بکنه که سروری که باهاش تماس گرفته واقعا همونیه که می خواسته و نه یک سرور دیگه. چطوری می فهمه؟ برای اینکه این بررسی بشه اصالت certificate اون سایت رو بررسی میکنه. یکی از چیزای که اصالت cert رو مشخص می کنه اینه که 1) از یک جای معتبر صادر شده باشه 2) و اینکه cert برای همونی صادر شده باشه که کاربر درخواست داده. یعنی اگه شما سایت www.iran.com رو درخواست دادی ولی cert ایی که دریافت کردی برای www.akhoond.com هست می فهمی یه جای کار می لنگه.  حالا این allowinsecure میگه بیخیال تصدیق certificate شو.

**Comment by theduckperson** [comment]
ممنونم از توضیحات مفصلتون! همه قسمت‌ها رو متوجه شدم جز نکته‌ی چهارم. منظورتون چه نوع شنودی هست؟ اگر صرفا certificate بررسی نمیشه، من اینطوری متوجه شدم که یعنی بهرحال تونل بین کاربر و یوزر رمزنگاری شده. (مثلا درحالتی که sni رو چیزی به جز ادرس پروکسی قرار بدیم و allowinsecure رو فعل کنیم) اگر نشده، خطری که وجود داره اینه که پکت اول که داره مقصد رو مشخص میکنه لو میره فقط؟ (+ مقصدی که http باشه)

**Comment by iranxray** [comment]
> ممنونم از توضیحات مفصلتون! همه قسمت‌ها رو متوجه شدم جز نکته‌ی چهارم. منظورتون چه نوع شنودی هست؟ اگر صرفا certificate بررسی نمیشه، من اینطوری متوجه شدم که یعنی بهرحال تونل بین کاربر و یوزر رمزنگاری شده. (مثلا درحالتی که sni رو چیزی به جز ادرس پروکسی قرار بدیم و allowinsecure رو فعل کنیم) اگر نشده، خطری که وجود داره اینه که پکت اول که داره مقصد رو مشخص میکنه لو میره فقط؟ (+ مقصدی که http باشه)

دقیقا. خطر لو رفتن بسته اول وجود داره.
