### ISSUE TITLE
server filtered? 

### ISSUE THREAD

**Issue by sun01234** [iranxray/hope#39]
How would I know that my server is compromised and those ****  filtered my server?

**Comment by iranxray** [comment]
خیلی ساده است. اگه کانفیگ‌هاتون کار نمی‌کنه یعنی IP سرور شما به احتمال بالا کثیف شده. در مستند پرسش‌ها و پاسخ‌های متداول این رو گفته بودیم:

https://github.com/iranxray/hope/blob/main/faq.md

![image](https://user-images.githubusercontent.com/118040490/215850729-fc7c2ce6-5596-4b9c-9d57-097b04b5f82e.png)
