### ISSUE TITLE
The order of mark down files

### ISSUE THREAD

**Issue by amirsarfar** [iranxray/hope#4]
It would be very nice if we had the order of files prefixed to the file names.

1-buy-server.md
...

**Comment by iranxray** [comment]
ممنون. به نظر می‌اید که این مورد ضروری و حتی ممکن نباشد. انتظار این هست که خواننده از روی متن و با توجه به هایپرلینک‌ها قدم‌ها را بتواند دنبال کند.

**Comment by iranxray** [comment]
![image](https://user-images.githubusercontent.com/118040490/203473007-518ec5d2-d2a4-4ef9-a96c-d39f082b4b57.png)
