### ISSUE TITLE
connection time out

### ISSUE THREAD

**Issue by IranDotCom** [iranxray/hope#40]
سلام وقتی sshمیخوام بزنم برای اتصال به سرور این ارور رو میده >>>>  connection time out
سرور رو پینگ میکنم ریپلای میده و مشکلی نداره .ممنون میشم راهنمایی بفرمائید

**Comment by Amiero** [comment]
به احتمال زیاد آی پی تون بلک لیست شده، من هم همین مشکل رو داشتم

**Comment by IranDotCom** [comment]
مگه بلک لیست شده باشه پینگ میکنی نباید تایم اوت بده.این کامل ریپلای میده حتی یدونه تایم اوت نمیده

**Comment by iranxray** [comment]
نتیجه ping و یا حتی telnet نشون نمیده که IP شما فیلتر شده یا نه. فیلترچی می‌تونه فقط یه نوع ارتباط خاصی رو ببنده و بقیه انواع باز باشه. اگه در ساخت کانفیگ‌ها همه مسائلی که گفتیم رو رعایت کردید و باز جواب نگرفتید، احتمالا نیاز به تغییر IP و دامنه دارید. برای تغییر دامنه نیاز به خرید نیست. می‌تونید از یک subdomain دیگه استفاده کنید.

**Comment by Amiero** [comment]
برای من بلاک شده قطعا ولی پینگ میداد با تغییر آی پی مشکل حل شد.
