### ISSUE TITLE
server got filtered in 2 days

### ISSUE THREAD

**Issue by sun01234** [iranxray/hope#41]
salam 
man ba tavajoh be proje Hope hame marahelo raftam vali ta alan 3 bar filter shodam 
dafe akhar faght 2 rooz tool keshid ta filter besham faghat 2 rooz !
ba inke hardafe IP sozoondam domain jadid kharidam .net va .com vali in dafe to 2 rooz filter shod 
mamnoon misham behem begid chikar konam vaghean moondam

**Comment by iranxray** [comment]
متاسفم. میشه بگید چه کانفیگ هایی رو روی سرور داشتید؟ از چه پورت هایی استفاده کردید؟ آیا لحاظ کردید که با استفاده از پروکسی به سایت ها و اپ های ایرانی سر نزنید؟

**Comment by iranxray** [comment]
پیشنهاد می‌کنیم حتما تنظیمات routing هم اعمال کنید.

https://github.com/iranxray/hope/blob/main/routing.md

**Comment by sun01234** [comment]
ممنون برا پاسخگوییتون 
من هم تروجان + tls و هم vless+xts+tcp داشتم روی پورت 443 و 80 همه چیزش اوکی بود 
اره استفاده نکردیم از سایت ایرانی ولی اگه یه درصد کسی استفاده کرده باشه از این سایتا ممکنه توی دو روز شناسایی و فیلتر بشه؟حتی کمتر از  دو روز بود یک روز و چندین ساعت

خیلی ممنون از راهنماییتون
اگه روتینگ هم جواب نداد بعدش DNS رو انجام بدم؟
و بعد اون دیگه راهی نیست؟


> متاسفم. میشه بگید چه کانفیگ هایی رو روی سرور داشتید؟ از چه پورت هایی استفاده کردید؟ آیا لحاظ کردید که با استفاده از پروکسی به سایت ها و اپ های ایرانی سر نزنید؟

**Comment by iranxray** [comment]
متاسفانه سرعت شناسایی سرورها به نسبت قبل بالاتر رفته. توصیه می‌کنیم آموزش routing رو هم سمت سرور و هم سمت کلاینت انجام بدید. داریم کار می‌کنیم تا بیشتر بفهمیم چه اتفاقی داره میوفته. چیزی فهمدیدم خبرتون می‌کنیم 🤞

**Comment by sun01234** [comment]
واقعا دمتون گرم و خسته نباشید 3>
