### ISSUE TITLE
آموزش مشکل دار routing

### ISSUE THREAD

**Issue by radio-azad-iran** [iranxray/hope#42]
آموزش داده شده هم سخت هست و هم گمون کنم با core 1.7.3 کار نکنه
به علاوه داره سایت های پورن رو میبنده
خود این پروژه xray آی پی های هر کشور رو داره، حتی اگه ناقصه باید براشون issue بزنیم که تو geo files شون اضافه کنن
تنها کار لازم بلاک کردن geoip:ir سمت سرور هست که ir مخفف Iran هست
به علاوه بد نیست تو انتهای آموزش، قسمتی اضافه بشه که تو کلاینت چطور geoip:ir رو direct کنن که احتیاجی به خاموش روشن کردن vpn نباشه
به علاوه تو قسمت مزایای پست تلگرام بهتره به کاهش بار سرور و هزینه ها هم اشاره بشه
من تنظیمات کامل رو میگذارم، ولی در کل اون routing strategy اش لازمه که IP if non matched باشه و geoip:ir برابر با blocked
محتوای زیر در صفحه xui/setting تو تب xray config زده بشه، فقط همین
بعد کامنت های پست های تلگرام تون رو هم ممنون میشم باز کنید

**Comment by radio-azad-iran** [comment]
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "ip": [
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by radio-azad-iran** [comment]
`{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "ip": [
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}`

**Comment by iranxray** [comment]
@radio-azad-iran 

دم شما گرم و خیلی ممنون از پیشنهاد‌های خوب‌تون. تقریبا همشون رو اعمال کردیم.

۱. دستور مربوط به porn‌ حذف شد.
۲. مزایایی که گفتید در مستند امید و پست تلگرام اضافه شد.
۳. مسدود سازی بر اساس ip هم به کانفیگ اضافه شد و در انتها هم توضیحی اضافه شد که فهرست ip ها چگونه تهیه شده.
۴. ما ترجیح میدیم که همچنان از دامنه‌ها هم استفاده کنیم، چون سرعت تغییر دامنه‌ها کمتر از تغییرات مربوط به ip هاست. 
۵. در کانفیگ اولیه نیازی به استفاده از `IPIfNonMatch` نبود، چون اساس از IP‌ برای مسدود سازی استفاده نمی‌کردیم. به طور پیش‌فرض فقط نام دامنه بررسی میشد ‍‍`AsIs`.
۶. هم کانفیگ قدیم و هم کانفیگ جدید با نسخه 1.7.3‌ هم سازگار هستند.
۷. مسدود سازی سمت کاربر اضافه شد.
۷. در مورد باز کردن کامنت‌ها نیاز به مشورت بیشتر داریم.

**Comment by iranxray** [comment]
قسمت اضافه کردن دامنه‌ها به تنظیمات را در گامی اختیاری قرار دادیم. باز هم ممنون.
