### ISSUE TITLE
فیلدهای cert , key  در هنگام ساخت کانفیگ 

### ISSUE THREAD

**Issue by whereisafshin** [iranxray/hope#43]
سلام ، تو بخش ساخت کانفیگ وقتی TLS  رو میزنیم دامنه و cert , key باید پر بشه ، قسمت دامنه مشخص هستش ، دو بخش دیگه رو من از طریق این اسکریپت acme.sh کلید ساختم ( یوتیوب و سایتهای دیگه هم از این اسکریپت استفاده میکردن برای SSL)  آیا این معتبر هستش یا راه بهتری پیشنهاد دارید؟ و از کلادفلر بصورت api هم شنیدم میشه ssl رو به سرور متصل کرد آیا اینم معتبر هستش؟ 
https://seakfind.github.io/2021/10/10/X-UI/
آدرس سایتی که اسکریپت استفاده کرده

**Comment by iranxray** [comment]
سلام. چرا از مستند امید برای ساخت certificate استفاده نمی‌کنید؟

https://github.com/iranxray/hope/blob/main/create-tsl-certificate.md

به نظر ما استفاده از certbot‌ از باقی روش‌ها ساده‌تر هست. البته certbot هم در پس صحنه از acme استفاده می‌کنه.

**Comment by whereisafshin** [comment]
من کلا هرچی یاد گرفتم از آموزش های شما بود ، این بخش cert و key که certbot میده به پسوند pem اونا رو تو بخش tls وارد کنیم یا اصلا نیازی نیست به این  همه کانفیگ ها TLS  میشن با زدن تیک tls

**Comment by iranxray** [comment]
وقتی که فایل‌های PEM تولید شد باید از اون‌ها استفاده کنید که TLS رو بتونید فعال کنید. در ساخت تروجان و VLESS گفتیم که از چه فایلی کجا باید استفاده کنیم:

![image](https://user-images.githubusercontent.com/118040490/216791342-7ce64088-156f-4524-9c2c-1b5335915fe5.png)
