### ISSUE TITLE
بروز رسانی نسخه xray پنل x-ui

### ISSUE THREAD

**Issue by whereisafshin** [iranxray/hope#47]
سلام میشه در مورد بروزرسانی نسخه xray پنل x-ui یه اموزش بدید پنلی چینی امکانات خاصی نداره . چندتا پنل انگلیسی هستش نسخه xray شون قدیمیه چطوری میشه اپدیتشون کرد

**Comment by iranxray** [comment]
حتما. به زودی اینکار رو انجام خواهیم داد. ممنون از شما.
