### ISSUE TITLE
مسدودسازی سایت‌ها و اپلیکیشن‌های ایرانی

### ISSUE THREAD

**Issue by hdd064** [iranxray/hope#49]
گام پنجم لینک اول باید اصلاح بشه
https://github.com/bootmortis/iran-hosted-domains/releases/download/202302041334/iran.dat

**Comment by iranxray** [comment]
می‌تونید به مورد ۱۰ از #45 مراجعه کنید. به زودی به مستندات رسمی اضافه میشه.

**Comment by xmha97** [comment]
> گام پنجم لینک اول باید اصلاح بشه https://github.com/bootmortis/iran-hosted-domains/releases/download/202302041334/iran.dat

سلام
از این فایل میتونم در برنامه‌ی NekoRay استفاده کنم؟

![image](https://user-images.githubusercontent.com/23485114/217497129-e142bae1-109c-4bb3-8bcf-b46eb07bfe3a.png)
