### ISSUE TITLE
couldn't connect on ir.a.n.c-e_ll

### ISSUE THREAD

**Issue by amirgi73** [iranxray/hope#52]
Hi i've tried almost all possible combinations (vless+ tls+ cdn / quick/ kcp/ grpc , trojan , ....)  and couldnt connect on irancell, many of this combinations work without problem on Hmrahe_av.al though! Have you guys any idea which protocol currently works on ircell?

**Comment by iranxray** [comment]
به زودی آموزش استفاده از vision و reality رو خواهیم گذاشت.
