### ISSUE TITLE
دامین استثنا

### ISSUE THREAD

**Issue by hdd064** [iranxray/hope#54]
یه دامین ir رو اینجا چجوری میشه استثنا کرد؟

**Comment by whereisafshin** [comment]
تو قسمت block بزار دامنه تو . تو کلاینت خودت هرچی که هستش اون دامنه از قسمت روتینگ که بهش میگن تو قسمت block بزار تا از وی پی ان رد بشه

**Comment by hdd064** [comment]
توی x-ui منظورم بود

**Comment by whereisafshin** [comment]
> توی x-ui منظورم بود

تو پنل برای همه ست میشه ، استثنا برای یوزر نمیتونی قائل بشی مگه اینکه فایل کانفیگ اون کاربر رو ادیت کنی

**Comment by hdd064** [comment]
استثنا برای یه دامین روی x-ui
نه استثنا کردن یوزر

**Comment by iranxray** [comment]
@hdd064 

۱.‌ هیچ ترافیکی نباید از سرور‌تون به داخل بیاد.

۲. روی گوشی یا کلاینت از روش direct استفاده کنید تا دسترسی به سایت‌های داخلی باز باشه. یعنی به کلاینت بگید اصلا ترافیک داخل رو از پروکسی عبور نده. قسمت "مسدودسازی از سمت کاربر" رو در مستند routing ببینید و حتما انجام بدید.

**Comment by hdd064** [comment]
مشکل اینه که vpn روی دامین ir هست با vpn خودم نمیتونم بهش وصل بشم :)
