### ISSUE TITLE
قطع دسترسی به پنل x-ui پس از جایگزین کردن تنظیمات

### ISSUE THREAD

**Issue by Artin70** [iranxray/hope#56]
سلام
وقت بخیر
من دو سرور دارم و پس از انجام گام پنجم و جایگزین کردن تنظیمات، روی یکی فقط با همراه اول بدون وی‌پی‌ان و با بقیه اینترنت‌ها با وی‌پی‌ان به پنل دسترسی دارم، روی سرور دیگه فقط با همراه اول و بدون وی‌پی‌ان.  من از این اسکریپت پنل x-ui استفاده می‌کنم:

https://github.com/HexaSoftwareTech/x-ui

چطوری میتوننم این مشکل عدم دسترسی به پنل رو برطرف کنم؟

سپاس

**Comment by mostafa3053** [comment]
سلام
احیانا دامنه ای که استفاده می کنید .ir نیست؟! اگر دامنه آی آر باشه مشکل میخورید
