### ISSUE TITLE
دسترسی مستقیم بدون پروکسی به سایت‌های ایرانی به‌جای مسدودسازی

### ISSUE THREAD

**Issue by Artin70** [iranxray/hope#59]
سلام
وقت بخیر

طبق آموزش و کدی که برای Routing از سمت سرور گذاشتید، دسترسی به سایت‌ها و آی‌پی‌های ایرانی توسط این روش مسدود میشه. چرا مثل آموزشی که برای Routing از سمت کلاینت گذاشتید، به‌جای مسدودسازی، دسترسی مستقیم (Direct) بدون گذر از پروکسی رو برای سایت‌های ایرانی داخل کدهای سمت سرور درنظر نگیریم؟ با این روش هم ریسک فاش شدن آی‌پی از بین میره و هم کاربر مجبور نیست برای دسترسی به اون سایت ایرانی اتصالش از VPN رو قطع کنه.

سپاس

**Comment by hdd064** [comment]
> سلام وقت بخیر
> 
> طبق آموزش و کدی که برای Routing از سمت سرور گذاشتید، دسترسی به سایت‌ها و آی‌پی‌های ایرانی توسط این روش مسدود میشه. چرا مثل آموزشی که برای Routing از سمت کلاینت گذاشتید، به‌جای مسدودسازی، دسترسی مستقیم (Direct) بدون گذر از پروکسی رو برای سایت‌های ایرانی داخل کدهای سمت سرور درنظر نگیریم؟ با این روش هم ریسک فاش شدن آی‌پی از بین میره و هم کاربر مجبور نیست برای دسترسی به اون سایت ایرانی اتصالش از VPN رو قطع کنه.
> 
> سپاس

چون از نظر فنی امکانش نیست، کاربر وارد یه سایت میخواد بشه، درخواست میره به سرور vpn، اینجا vpn یا میتونه بلاک کنه یا از طریق خودش دیتا رو برسونه به یوزر. برای همین این قضیه فقط از سمت کاربر میتونه انجام بشه. ینی کلاینت کلا درخواست رو به سرور vpn نفرسته.

**Comment by iranxray** [comment]
@Artin70 

۱. در سمت سرور فقط می‌تونیم ترافیک رو بلاک کنیم.
۲. در سمت کلاینت می‌تونیم ترافیک رو direct کنیم. یعنی می‌تونیم بگیم ترافیک داخلی از پروکسی رد نشه و ترافیک خارجی رد بشه. در مستند Routing قسمت "مسدودسازی از سمت کاربر" رو ببینید و حتما انجام بدید.

**Comment by Artin70** [comment]
> چون از نظر فنی امکانش نیست، کاربر وارد یه سایت میخواد بشه، درخواست میره به سرور vpn، اینجا vpn یا میتونه بلاک کنه یا از طریق خودش دیتا رو برسونه به یوزر. برای همین این قضیه فقط از سمت کاربر میتونه انجام بشه. ینی کلاینت کلا درخواست رو به سرور vpn نفرسته.

من یه مشکلی که دارم اینه که بعد از انجام Routing، پنلم فقط روی کامپیوتر باز میشه. روی گوشی فقط با وی پی ان با آی پی همون سروری که روش ترافیک رو از این روش بلاک کردم باز میشه. قبل از انجام این روش، روی گوشی بدون VPN باز نمیشد ولی با هر وی پی انی باز میشد.

راهی نیست که این مشکل رو بشه حل کرد؟

**Comment by xshayank** [comment]
با اینکه بسته شده
ولی من یه نظر دارم بدم
نمیشه از warp استفاده کرد؟
چون يه اسكريپت هست كه مياد روي سرور warp رو پروکسی میکنه و با یه کانفیگ راحت میشه گوگل و یه عالمه سایت دیگه رو انداخت روش
این راه جواب نمیده؟
من فقط نمیدونم چیکار کنم همه درخواست ها بره رو پراکسی

**Comment by iamomid1997** [comment]
با درود و وقت بخیر خدمت دوستان
بنده کسی (موبایل فروش) رو میشناسم که از یه بات تلگرامی کانفیگ میگیره و میفروشه و کانفیگ هاش سایت های داخلی رو دایرکت میکنه یعنی بدون اینکه نیازی به خاموش کردن VPN باشه سایت ها و برنامه های بانکی بالا میاد
طرف هیچ کار اضافه ای روی v2rayNG یا هر کلاینت دیگه انجام نمیده صرفا کانفیگ رو میخره و برا مشتری میزنه
کسی نظری نداره که چطوری اینکار صورت گرفته؟

**Comment by iamomid1997** [comment]
> با درود و وقت بخیر خدمت دوستان بنده کسی (موبایل فروش) رو میشناسم که از یه بات تلگرامی کانفیگ میگیره و میفروشه و کانفیگ هاش سایت های داخلی رو دایرکت میکنه یعنی بدون اینکه نیازی به خاموش کردن VPN باشه سایت ها و برنامه های بانکی بالا میاد طرف هیچ کار اضافه ای روی v2rayNG یا هر کلاینت دیگه انجام نمیده صرفا کانفیگ رو میخره و برا مشتری میزنه کسی نظری نداره که چطوری اینکار صورت گرفته؟

در ادامه صحبت هام این رو هم اضافه کنم که اگر از یه سرور ایران به عنوان سرور تانل استفاده کنیم و از روش پنل به پنل دوکودمو برای تانل سرور ایران به خارج استفاده کنیم احتمال زیاد بشه روی تنظیمات روتینگ پنل سرور ایران تغییراتی داد که بشه سایت ها و آی پی های ایرانی دیگه به سمت سرور خارج ارسال نشه و مستقیم با آی پی سرور ایران لود بشه و بالا بیاد
