### ISSUE TITLE
اضافه کردن کلاینت برای آیفون

### ISSUE THREAD

**Issue by theduckperson** [iranxray/hope#6]
سلام. کلاینت shadowlink از پروتکل vmess و trojan پشتیبانی می‌کنه. برای vless هم می‌شه از napsternetv استفاده کرد؛ اما این اپلیکیشن برای نصب به ios15 و بالاتر نیاز داره.

**Comment by iranxray** [comment]
ممنون. توضیحات به مقاله نصب کلاینت در آیفون استفاده شد.

https://github.com/iranxray/hope/commit/712404470bfe10484d555d2e54c93a324c1be8cc

**Comment by iranxray** [comment]
ممنون. مقاله آیفون کلا به NapsternetV بازنویسی شد.

https://github.com/iranxray/hope/blob/main/install-iphone.md
