### ISSUE TITLE
مشکل بعد از بروزرسانی x-ui درباره کد مربوط به مسدود سازی س

### ISSUE THREAD

**Issue by mahsamcse** [iranxray/hope#61]
با درود
کدی که در قسمت Xray Config برای مسدود سازی سایت های ایرانی وارد کردیم بعد از بروزرسانی پنل x-ui به نسخه 3.4 (FranzKafkaYu) 
xray ارو میده و کار نمکینه 
و با برگشت به کد قبلی مشکل حل میشه
ممنون میشم کد مربوطه رو بروزرسانی کنید

**Comment by Malekiyan** [comment]
Hi
After each update, you have to run the following commands:

sudo -i
cd /usr/local/x-ui/bin
wget https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
wget https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
