### ISSUE TITLE
How to block Iranian sites x-ui panel (Forked by hossein asadi)

### ISSUE THREAD

**Issue by AlexRooter** [iranxray/hope#65]
This Config for hossein asadi panel

I love Iranian people & Country
--------------------------------------
These settings work correctly with this panel and you will no longer have the problem of Iranian programs being opened by users. Good luck
--------------------------------------
x-ui url/panel setting/xray Configuration
--------------------------------------

{
"log": {
"loglevel": "warning",
"access": "./access.log"
},

"api": {
"services": [
"HandlerService",
"LoggerService",
"StatsService"
],
"tag": "api"
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 62789,
"protocol": "dokodemo-door",
"settings": {
"address": "127.0.0.1"
},
"tag": "api"
}
],
"outbounds": [
{
"protocol": "freedom",
"settings": {}
},
{
"protocol": "blackhole",
"settings": {},
"tag": "blocked"
}
],
"policy": {
"levels": {
"0": {
"statsUserUplink": true,
"statsUserDownlink": true
}
},
"system": {
"statsInboundDownlink": true,
"statsInboundUplink": true
}
},
"routing": {
"rules": [
{
"inboundTag": [
"api"
],
"outboundTag": "api",
"type": "field"
},
{
"ip": [
"geoip:private",
"geoip:ir"
],
"outboundTag": "blocked",
"type": "field"
},
{
"outboundTag": "blocked",
"protocol": [
"bittorrent"
],
"type": "field"
},
{
"outboundTag": "blocked",
"domain": [
"regexp:.*\.ir$",
"ext:iran.dat:ir",
"ext:iran.dat:other",
"geosite:category-ir-gov",
"geosite:category-ir-news",
"geosite:category-ir-bank",
"geosite:category-ir-tech",
"geosite:category-ir-travel",
"geosite:category-ir-shopping",
"geosite:category-ir-insurance",
"geosite:category-ir-scholar",
"snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
],
"type": "field"
}
]
},
"stats": {}
}

**Comment by mahdikf78** [comment]
درود. در پنل کافکا اضافه کردم اما Error داده.
![2023-05-09_122238](https://user-images.githubusercontent.com/113425634/237045628-8327c32c-2c97-4459-bfe5-4e61808ab9e3.jpg)
