### ISSUE TITLE
تغییر مسیر درخواست سایت داخلی به یک آدرس دیگر

### ISSUE THREAD

**Issue by ahooee** [iranxray/hope#67]
سلام 
امکانش هست ، وقتی کاربر یک سایت خاص (مثلا یک سایت داخلی)رو  در مرورگرش وارد میکنه ، یه سایت دیگه ای براش نمایش داده بشه 

با  dns server اختصاصی میدونم میشه ولی میخوام بدونم خود v2ray  امکانی داره که با یک کانفیگ ساده این کار رو انجام داد؟

**Comment by iranxray** [comment]
نخیر. Xray امکان ویرایش درخواست کاربر رو نمیده.

**Comment by xshayank** [comment]
با اینکه بسته شده
ولی من یه نظر دارم بدم
نمیشه از warp استفاده کرد؟
چون يه اسكريپت هست كه مياد روي سرور warp رو پروکسی میکنه و با یه کانفیگ راحت میشه گوگل و یه عالمه سایت دیگه رو انداخت روش
این راه جواب نمیده؟
من فقط نمیدونم چیکار کنم همه درخواست ها بره رو پراکسی

https://github.com/fscarmen/warp
این رو میگم




توی یکی دیگه هم نوشتم این رو
