### ISSUE TITLE
محدودیت دسترسی آیپی های ایران در برنامه NapsternetV

### ISSUE THREAD

**Issue by mostafa3053** [iranxray/hope#69]
ممنون بابت تاپیک بسیار مفیدی که ایجاد کردید
 با توجه به اینکه اگر بخوایم کانفیگ رو بدیم کسی استفاده کنه ممکنه پخش بشه بنابراین من از برنامه NapsternetV برای اتصال استفاده میکنم و با hardwarecode اون کانفیگ رو قفل میکنم که فقط روی سیستم خودش استفاده بشه (همچنین چون نسخه IOS هم داره کار رو راحت میکنه برای کسانی که اپل دارن و همه از یه نرم اقزار استفاده میکنند)
اما مشکلی که برام پیش آمده اینه که میخواستم روی این فایل کانفیگ تغییراتی اعمال کنم که IP های ایران رو هم مستقیم وصل بشه و از پروکسی عبور نکنه مشابه همین مورد که توضیح داده شده برای برنامه V2rayNG ممنون میشم راهنمایی کنید در NapsternetV چطور باید این تغییرات ایجاد بشه؟ خودم تلاش کردم فایل کانفیگ رو ویرایش کنم اما با پیامی روبرو شدم که میگه failed to load geoip:ir

**Comment by hamihastam** [comment]
سلام فکر کنم باید فایل json که از پنل خودتون میگیرید رو ویرایش کنید و روتینگشو عوض کنید بعد وارد نپستر کنید و از اونجا کانفیگ رو کلون کنید.

**Comment by mostafa3053** [comment]
سلام بله درسته اما مشکل اینجاست که وقتی ویرایش میکنم پیام خطا میده که geoip:ir رو نمیشناسه! فکر میکنم فایل های مربوط به geoip و geosite رو نداره! و نمیدونم چطور باید بهش اضافه کنم!

**Comment by iranxray** [comment]
سلام. متاسفیم بابت تاخیر در پاسخگویی. به دلایلی مجبور به توقف فعالیت شدیم. در مورد سوال شما به زودی آموزش هایی رو خواهیم داشت برای استفاده از Reality و Vision. اگر در ios از اپلیکیشن Wings X استفاده کنید می تونید از فایلهای json برای کانفیگ استفاده کنید. سوالی بود حتما بگید.
