### ISSUE TITLE
دامین داخلی

### ISSUE THREAD

**Issue by Meytiz** [iranxray/hope#73]
سلام 
من میخوام یک دامین داخلی خاص مسدود نشه چه حرکتی باید بزنم؟

**Comment by iranxray** [comment]
سلام دوست عزیز. به دلیل مسائل امنیتی و مشکلی  که برای یکی از ما پیش اومده بود نتونستیم پاسخگو باشیم. حالا برگشتیم. راه حل ساده است. می تونید در قسمت routing چیزی شبیه زیر رو اضافه کنید:
```json
 {
        "outboundTag": "freedom",
          "domain": ["MYDOMIAN"],
        "type": "field"
 }
```
