### ISSUE TITLE
تشریح الگوریتم های فیلترینگ جدید اعمال شده

### ISSUE THREAD

**Issue by SAEEDZZZ** [iranxray/hope#74]
سلام وقت بخیر 
دوستان همونطور که مطلع هستید با فعال شدن tls استفاده از کلادفلر اختلال و کندی شدید هست در صورت کانکت شدن
به جز پیدا کردن آیپی سالم که واقعا داستان شده کسی متد پیشنهادی دیگه ای داره؟ 
و اینکه کسی مقاله یا اطلاعاتی راجب اینکه این متد جدید به چه صورته که آیپی ها بلاک شدن ولی مشکلی تو لود شدن سایت های مرتبط با کلاد فلر وجود نداره

**Comment by iranxray** [comment]
سلام دوست عزیز. متاسفیم که دیر جواب تون رو میدیم. برای برخی از اعضای تیم مشکلی پیش اومده بود که مانع فعالیت ما شد. به زودی روش های جدید مبتنی بر Reality و Vision رو توضیح میدیم. روش های قبلی مبتنی بر VLESS و Trojan از نظر تیم Xray منسوخ شدند، لو رفتند و نباید استفاده بشن.
