### ISSUE TITLE
IR domains & How to by pass them through the Server side 

### ISSUE THREAD

**Issue by Phoenix-999** [iranxray/hope#76]
Hi 
Is there anyway that we can bypass some of the Iranian websites instead of blocking them while the VPN is on through the server and U-XI panel. 

![Screenshot 2023-03-13 at 10 55 45](https://user-images.githubusercontent.com/127796122/224837597-d50a8ddd-7f5a-469b-937d-031bc4362eb2.png)

Ps: Thank you all so very much for all your assistance through this tough times.✌🏾

**Comment by iranxray** [comment]
سلام دوست عزیز.

پیشتر در قسمت 'مسدود سازی سمت کاربر' توضیح دادیم که چطور میشه IP های داخلی رو دور زد و یا به اصطلاح Bypass k کرد.

https://github.com/iranxray/hope/blob/main/routing.md#%D9%85%D8%B3%D8%AF%D9%88%D8%AF%D8%B3%D8%A7%D8%B2%DB%8C-%D8%A7%D8%B2-%D8%B3%D9%85%D8%AA-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1
