### ISSUE TITLE
پنل جدید v2ray 

### ISSUE THREAD

**Issue by vahidxo** [iranxray/hope#77]
سلام دوستان وقت بخیر
تو یکی از کانال‌های فروش وی پی ان الان این عکس رو دیدم خواستم بدونم کسی اطلاعی از اسم تم یا قالب این سایت داره؟
weepeen.site اینم آدرس سایته
![image](https://user-images.githubusercontent.com/122749732/226212903-672a6ac9-6308-432d-93d9-f2e3d7866f1d.png)

**Comment by Bardiafa** [comment]
گمون میکنم XMPLUS باشه با کمی تغییر تو ui سایت @vahidxo

**Comment by hlradorgnai-collab** [comment]
پنل
