### ISSUE TITLE
انتقال دامنه های ایرانی به آیپی اصلی اینترنت کاربر به جای مسدود سازی

### ISSUE THREAD

**Issue by rbakhshi72** [iranxray/hope#78]
سلام، این روش خیلی خوب بود و من تستش کردم و سایتهای ایرانی برام باز نمیشند ولی آیا راهی هست که به جای مسدود سازی سایتهای ایرانی، آون ها رو از پراکسی خارج کنیم و با آیپی اصلی اینترنت خود کاربر براش سایت باز بشه؟
این شکلی کاربر همش باید فیلتر شکن رو خاموش و روشن کنه.

**Comment by rbakhshi72** [comment]
راستی من از طریق روش دوم که داخل پنل x-ui باید تغییرات رو اعمال کنیم، انجام دادم.

**Comment by rbakhshi72** [comment]
کسی نیست که جواب من رو بده؟

**Comment by iranxray** [comment]
سلام دوست عزیز.

پیشتر در قسمت 'مسدود سازی سمت کاربر' توضیح دادیم که چطور میشه IP های داخلی رو دور زد و یا به اصطلاح Bypass k کرد.

https://github.com/iranxray/hope/blob/main/routing.md#%D9%85%D8%B3%D8%AF%D9%88%D8%AF%D8%B3%D8%A7%D8%B2%DB%8C-%D8%A7%D8%B2-%D8%B3%D9%85%D8%AA-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1

**Comment by NovinSystem** [comment]
سلام بزرگوار @iranxray 
درست میفرمایید قبلا گفتید اما متاسفانه کار نمیکنه و انگار سایت های ایرانی رو داره بلاک میکنه
من خودم تا الان mojavez.ir و saka.epolice.ir رو این مشکل رو داشتم
