### ISSUE TITLE
استفاده در xrayr

### ISSUE THREAD

**Issue by alijoon3376** [iranxray/hope#84]
با سلام 
دوستان امکانش هست راهنمایی بفرمایید چجوری میشه ایپی و دامنه های ایران رو در هسته xrayr بلاک کرد ؟
https://github.com/XrayR-project/XrayR

**Comment by Phoenix-999** [comment]
🔴مسدودسازی سایت‌ها و اپلیکیشن‌های ایرانی

https://github.com/iranxray/hope/blob/main/routing.md
