### ISSUE TITLE
فیلتر شدن ip

### ISSUE THREAD

**Issue by MiladHossein** [iranxray/hope#85]

**Comment by aminkalan66** [comment]
سلام من سرورم کمتر از ۲۴ ساعت فیلتر شد، راهکاری چیزی هست بتونم درستش کنم؟؟
از روش روترینگ و مسدود سازی آی پی های ایران هم استفاده کزده بودم، پروتوکل هم از reality استفاده کرده بودم.

**Comment by MiladHossein** [comment]
عجیبه چرا متن ایشو من نیومده 

برای منم همین اتفاق افتاد . من حدث میزنم که لیک از گوشی های اندروید اتفاق میوفته 
یه حدث دیگه هم اینه که نباید از سایت های معروف ایرانی برای ریلیتی استفاده کرد . 
من از آپارات استفاده کردم . چیزی که فکر میکنم ( اثباتی براش ندارم ) اینه که فیلترچی می تونی ای پی سرور رو با ip که مثلا از آپارات داره مقایسه کنه  و بفهمه که اشتباهه

**Comment by aminkalan66** [comment]
> عجیبه چرا متن ایشو من نیومده
> 
> برای منم همین اتفاق افتاد . من حدث میزنم که لیک از گوشی های اندروید اتفاق میوفته یه حدث دیگه هم اینه که نباید از سایت های معروف ایرانی برای ریلیتی استفاده کرد . من از آپارات استفاده کردم . چیزی که فکر میکنم ( اثباتی براش ندارم ) اینه که فیلترچی می تونی ای پی سرور رو با ip که مثلا از آپارات داره مقایسه کنه و بفهمه که اشتباهه

بعد از این اتفاق، راهی جز تعویض سرور و آی پی نیست؟

**Comment by MiladHossein** [comment]
شاید بشه با بردنش پشت کلادفلر سرور رو دوباره به صورت محدود استفاده کرد

**Comment by aminkalan66** [comment]
> شاید بشه با بردنش پشت کلادفلر سرور رو دوباره به صورت محدود استفاده کرد

آموزشی ازش دارید که من بتونم تست بکنم ؟
