### ISSUE TITLE
اتصال و استفاده از نت ایرانسل

### ISSUE THREAD

**Issue by mahdikf78** [iranxray/hope#89]
با سلام. دوستانی که از روش Reality استفاده میکنن آیا میتونن با اینترنت ایرانسل به خوبی به VPN متصل بشن؟ طبق تست هایی که داشتم با تمام اپراتورها کار میکنه به جز ایرانسل. راه حلی برای این مشکل هست؟ یا فقط من مشکل دارم؟

**Comment by iranxray** [comment]
احتمالا ایرانسل بر روی IP سرور شما محدودیت اعمال کرده.
