### ISSUE TITLE
سوال در مورد راه اندازی

### ISSUE THREAD

**Issue by Issafarhad** [iranxray/hope#92]
سلام
من گفتم از خارج برام یه سرور ارزون بخرم
به نظرتون میتونم راه اندازی کنم و خونوادکی فیلتر شکن داشته باشیم؟
اگر گیر و گوری داشته باشم هل من ناصر ینصرنی؟

**Comment by Phoenix-999** [comment]
ما در این مقاله کوتاه آموزش می‌دهیم که چگونه می‌توانیم پلتفرم Xray را بر روی لینوکس نصب کنیم. اگر دسترسی به لینوکس ندارید، می توانید برای تهیه سیستم لینوکسی به [مستندات ما در این زمینه](https://github.com/iranxray/hope/blob/main/buy-server.md) رجوع کنید.

https://github.com/iranxray/hope/blob/main/install-xui.md
