### ISSUE TITLE
درخواست 

### ISSUE THREAD

**Issue by Issafarhad** [iranxray/hope#94]
دوستانی که وارد هستند و تهران هستند ممنون میشم یه پیام بدن باهاشون تماس بگیرم
۰۹۳۳۱۵۷۱۴۱۷

**Comment by Phoenix-999** [comment]
@Issafarhad 
دوست عزیز در اینجا به علت مسائل امنیتی کسی به شما نمیتونه تماس مستقیم بگیره
توصیه میکنم شماره موبایل خودتونو از صفحه حذف کنید و ترجیحا از ایمیل یا آیدی تلگرام برای مکاتبه استفاده کنید
